call timed KPS_ATRI.TIM  >err
pause
call timed KPS_KMS1.TIM  >err
pause
call timed KPS_KMS2.TIM  >err
pause
call timed KPS_KMS3.TIM  >err
pause
call timed KPS_KZTI.TIM  >err
pause
call timed KPS_MDIN.TIM  >err
pause
call timed KPS_OMDT.TIM  >err
pause
call timed KPS_PY11.TIM  >err
pause
call timed KPS_PY21.TIM  >err
pause
call timed KPS_PY22.TIM  >err
pause
call timed KPS_PY31.TIM  >err
pause
call timed KPS_PY32.TIM  >err
pause
call timed KPS_RPY1.TIM  >err
pause
call timed KPS_RPY2.TIM  >err
pause
call timed KPS_UR1L.TIM  >err
pause
call timed KPS_UR1R.TIM  >err
pause
call timed KPS_UR2L.TIM  >err
pause
call timed KPS_UR2R.TIM  >err
pause
call timed KPS_UR3L.TIM  >err
pause
call timed KPS_UR3R.TIM  >err
pause
call timed KPS_UR4L.TIM  >err
pause
call timed KPS_UR4R.TIM  >err
pause
call timed KPS_WAIT.TIM  >err
pause
call timed KPM_MBET.TIM  >err
pause
call timed KPM_ATRI.TIM  >err
pause
call timed KPS_REBA.TIM  >err
pause
call timed KPM_KMS1.TIM  >err
pause
call timed KPM_KMS2.TIM  >err
pause
call timed KPM_KMS3.TIM  >err
pause
call timed KPB_ATRI.TIM  >err
pause
call timed KPM_KZTI.TIM  >err
pause
call timed KPM_MDIN.TIM  >err
pause
call timed KPM_OMDT.TIM  >err
pause
call timed KPM_PY11.TIM  >err
pause
call timed KPM_PY21.TIM  >err
pause
call timed KPM_PY22.TIM  >err
pause
call timed KPM_PY31.TIM  >err
pause
call timed KPM_PY32.TIM  >err
pause
call timed KPM_RPY1.TIM  >err
pause
call timed KPM_RPY2.TIM  >err
pause
call timed KPM_WAIT.TIM  >err
pause
call timed KPS_BET1.TIM  >err
pause
call timed KPS_BET2.TIM  >err
pause
call timed KPS_MBET.TIM  >err
pause
call timed KPS_BTG1.TIM  >err
pause
call timed KPS_BTG2.TIM  >err
pause
call timed KPS_BTG3.TIM  >err
pause
call timed KPS_BTR1.TIM  >err
pause
call timed KPS_BTR2.TIM  >err
pause
call timed KPS_BTR3.TIM  >err
pause
call timed KPB_KMS1.TIM  >err
pause
call timed KPB_KMS2.TIM  >err
pause
call timed KPB_KMS3.TIM  >err
pause
call timed KPB_KZTI.TIM  >err
pause
call timed KPB_MDIN.TIM  >err
pause
call timed KPB_OMDT.TIM  >err
pause
call timed KPB_PY11.TIM  >err
pause
call timed KPB_PY21.TIM  >err
pause
call timed KPB_PY22.TIM  >err
pause
call timed KPB_PY31.TIM  >err
pause
call timed KPB_PY32.TIM  >err
pause
call timed KPB_WAIT.TIM  >err
