
#ifndef _ADD_H_

#define _ADD_H_


extern void circle_move(short c, short sdx, short sdy, short *x, short *y);
extern long rnd(long max);

extern void rect_ef0(int writex,int writey,int mastx,int masty);
extern void rect_ef1(int writex,int writey,int mastx,int masty);
extern void rect_ef2(int writex,int writey,int mastx,int masty);
extern void rect_ef3(int writex,int writey,int mastx,int masty);
extern void rect_ef4(int writex,int writey,int mastx,int masty);
extern void rect_ef5(int writex,int writey,int mastx,int masty);

extern void fream_harf(short x,short y,short w,short h,short mx,short my);
extern void rect_ef00(int mastx,int masty,int wide,int high);

#endif

